[Messenger]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"

[Tiktok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
apkmirror-arch = "arm64-v8a"
build-mode = "module"
version = "beta"
included-patches = "'Alternative thumbnails' 'Ambient mode switch' 'Append time stamps information' 'Change homepage' 'Custom branding icon YouTube' 'Custom branding name YouTube' 'Custom double tap length' 'Custom package name' 'Custom playback speed' 'Custom player overlay opacity' 'Custom seekbar color' 'Default playback speed' 'Default video quality' 'Enable debug logging' 'Enable external browser' 'Enable gradient loading screen' 'Enable language switch' 'Enable minimized playback' 'Enable music search' 'Enable new splash animation' 'Enable new thumbnail preview' 'Enable seekbar tapping' 'Enable tablet mini player' 'Enable tablet navigation bar' 'Enable wide search bar' 'Force OPUS codec' 'Force fullscreen' 'Force video codec' 'Hide general ads' 'Hide video ads' 'Layout switch' 'MaterialYou' 'MicroG support' 'Overlay buttons' 'Premium heading' 'Quick actions components' 'Return YouTube Dislike' 'Sanitize sharing links' 'Settings' 'Shorts outline button' 'SponsorBlock' 'Spoof app version' 'Spoof device dimensions' 'Spoof player parameters' 'Swipe controls' 'Theme' 'Translations'"
exclusive-patches = true

[Twitch]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"

